string PROJECT_ID = "donCannoli-burns-kol-agent-memory";
string ALIAS_NAME = "kol-memory";
string BOOTSTRAP = "python3 ~/.kolmafia/scripts/kol-agent-memory/bootstrap_exact_tree.py install";
string SYNC = "python3 ~/.kolmafia/scripts/kol-agent-memory/bootstrap_exact_tree.py sync";

string strip_ws(string value) {
    matcher edges = create_matcher("^\\s+|\\s+$", value);
    return replace_all(edges, "");
}

string h(string value) {
    string out = replace_string(value, "&", "&amp;");
    out = replace_string(out, "<", "&lt;");
    out = replace_string(out, ">", "&gt;");
    out = replace_string(out, "\"", "&quot;");
    return out;
}

buffer page_shell(string title, string zone, string body) {
    buffer b;
    b.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">");
    b.append("<title>" + h(title) + "</title><style>:root{color-scheme:dark;--bg:#061011;--panel:#0b1b1d;--line:#1c3a3e;--text:#d9f0ec;--muted:#71928f;--cyan:#53e5d5;--amber:#ffba62}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.55 ui-monospace,monospace}.wrap{max-width:980px;margin:auto;padding:28px}.card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:18px;margin:12px 0}a{color:var(--cyan)}code,pre{background:#041012;border:1px solid var(--line);border-radius:7px;padding:2px 5px}.muted{color:var(--muted)}.tag{color:var(--amber);font-size:12px;letter-spacing:.12em}</style></head><body><main class=\"wrap\">");
    b.append("<div class=\"tag\">KOL-AGENT-MEMORY · " + h(zone) + "</div><h1>" + h(title) + "</h1>");
    b.append(body);
    b.append("<div class=\"card muted\">Master wiki after exact-tree bootstrap: <code>~/.kolmafia/kolmaf-ai/memory/llm-wiki.html5</code><br>Agent fallback index: <code>~/.kolmafia/data/kolmaf-ai.html5</code></div></main></body></html>");
    return b;
}

void write_generated(string path, buffer content) {
    if (!buffer_to_file(content, path)) {
        print("kol-agent-memory: failed to write " + path, "red");
    }
}

void write_session_index(string reason) {
    string body = "<div class=\"card\"><b>Generated session plane</b><p>This file is generated by the ASH control plane and contains only bounded runtime metadata.</p><pre>";
    body += "generated_at=" + now_to_string("yyyy-MM-dd'T'HH:mm:ss") + "\n";
    body += "reason=" + h(reason) + "\n";
    body += "player=" + h(my_name()) + "\n";
    body += "kolmafia_version=" + h(get_version()) + "\n";
    body += "kolmafia_revision=" + to_string(get_revision()) + "\n";
    body += "project_installed=" + to_string(git_exists(PROJECT_ID)) + "</pre></div>";
    body += "<div class=\"card\"><b>Boundary</b><p>Session evidence can inform reasoning but does not authorize a game-state mutation.</p></div>";
    write_generated("sessions/kolmaf-ai.html5", page_shell("KoLmaf-AI Session Memory Plane", "SESSION", body));
}

void write_runtime_state(string reason) {
    string [string] state;
    state["generated_at"] = now_to_string("yyyy-MM-dd'T'HH:mm:ss");
    state["reason"] = reason;
    state["player"] = my_name();
    state["kolmafia_version"] = get_version();
    state["kolmafia_revision"] = to_string(get_revision());
    state["project_id"] = PROJECT_ID;
    state["git_installed"] = to_string(git_exists(PROJECT_ID));
    state["master_wiki"] = "~/.kolmafia/kolmaf-ai/memory/llm-wiki.html5";
    state["agent_index"] = "~/.kolmafia/data/kolmaf-ai.html5";
    state["bootstrap_command"] = BOOTSTRAP;
    state["sync_command"] = SYNC;
    state["authority_note"] = "Memory/index surfaces inform; they do not authorize execution.";
    if (!map_to_file(state, "kol-agent-memory/runtime.tsv")) {
        print("kol-agent-memory: failed to write data/kol-agent-memory/runtime.tsv", "red");
    }
}

void refresh(string reason) {
    write_runtime_state(reason);
    write_session_index(reason);
    set_property("kolAgentMemoryLastRefresh", now_to_string("yyyy-MM-dd'T'HH:mm:ss"));
    set_property("kolAgentMemoryLastRefreshReason", reason);
    print("kol-agent-memory: KoLmafia-supported memory plane refreshed (" + reason + ").", "green");
}

void install_alias() {
    cli_execute("alias " + ALIAS_NAME + " => call kol-agent-memory.ash");
    print("kol-agent-memory: installed alias `" + ALIAS_NAME + "`.", "green");
}

void setup() {
    install_alias();
    refresh("setup");
    set_property("kolAgentMemoryBootstrapPending", "true");
    print("", "gray");
    print("Exact protected-path tree requires the bundled local bootstrap:", "blue");
    print(BOOTSTRAP, "green");
    print("", "gray");
    print("After it completes, run `call kol-agent-memory.ash refresh exact-tree-ready`.", "gray");
}

void status() {
    print("kol-agent-memory", "blue");
    print("  KoLmafia: " + get_version() + " / r" + get_revision());
    print("  player: " + my_name());
    print("  Git installed: " + git_exists(PROJECT_ID));
    print("  last refresh: " + get_property("kolAgentMemoryLastRefresh") + " (" + get_property("kolAgentMemoryLastRefreshReason") + ")");
    print("  master wiki: ~/.kolmafia/kolmaf-ai/memory/llm-wiki.html5");
    print("  agent index: ~/.kolmafia/data/kolmaf-ai.html5");
    print("  exact-tree bootstrap: " + BOOTSTRAP);
    print("  exact-tree sync: " + SYNC);
    print("  relay: choose kol-agent-memory-relay in the relay script selector");
}

void update_project() {
    if (!git_exists(PROJECT_ID)) {
        print("kol-agent-memory: project is not installed under KoLmafia Git.", "red");
        print("Install with: git checkout https://github.com/donCannoli-burns/kol-agent-memory", "gray");
        return;
    }
    boolean ok = cli_execute("git update " + PROJECT_ID);
    refresh(ok ? "git-update" : "git-update-failed");
    if (ok) {
        print("Templates updated. Regenerate protected-path pages with:", "blue");
        print(SYNC, "green");
    }
}

void help() {
    print("kol-agent-memory commands:", "blue");
    print("  status                    Show current integration state");
    print("  setup                     Install alias and refresh supported pages");
    print("  refresh [reason]          Refresh runtime/session metadata");
    print("  update                    KoLmafia git update + refresh");
    print("  bootstrap-command         Print exact-tree install command");
    print("  sync-command              Print exact-tree refresh command");
    print("  help                      Show this help");
}

void main(string command) {
    string cmd = strip_ws(command);
    string lower = to_lower_case(cmd);

    if (lower == "" || lower == "status") {
        status();
        return;
    }
    if (lower == "help") {
        help();
        return;
    }
    if (lower == "setup") {
        setup();
        return;
    }
    if (lower == "update") {
        update_project();
        return;
    }
    if (lower == "bootstrap-command") {
        print(BOOTSTRAP, "green");
        return;
    }
    if (lower == "sync-command") {
        print(SYNC, "green");
        return;
    }
    if (lower == "refresh" || starts_with(lower, "refresh ")) {
        string reason = "manual";
        if (length(cmd) > 7) reason = strip_ws(substring(cmd, 7));
        if (reason == "") reason = "manual";
        refresh(reason);
        return;
    }

    print("kol-agent-memory: unknown command: " + command, "red");
    help();
}
